import Head from "next/head";

import { Header } from "components/Header";
import { Hero } from "components/Hero";
import { Features } from "components/Features";
import { SalesManagement } from "components/SalesManagement";
import { PortfolioManagement } from "components/PortfolioManagement";
import { Stores } from "components/Stores";
import { Faq } from "components/Faq";
import { Banner } from "components/Banner";
import { Footer } from "components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quadra A</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link rel="icon" href="/favicons/android-chrome-192x192.ico" />
      </Head>
      <Header size="large" dark="inactive" />
      <main>
        <Hero />
        <Features />
        <SalesManagement />
        <PortfolioManagement />
        <Stores />
        <Faq />
        <Banner />
        <Footer />
      </main>
    </>
  );
}
